name: Run Tests and Upload Artifact #Nombre opciones

on: [push, pull_request] #Obligatorio, se indica cuando se va a ejecutar este evento. Esto quiere decir que las acciones que coloque en esta casilla, activara todos los jobs

jobs:
  test:
    runs-on: ubuntu-latest #Maquina virtual o donde quiera ejecutar esta tarea.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate report
        run: node test/calculator.test.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/test-results.txt
